//Create ↓
POST http://localhost:3000/api/posts
Content-Type:  application/json
 
 {
    "title": "Meu primeiro Post",
    "content": "Conteúdo do Post",
    "userId": 7
 }

###
//listar ↓
GET http://localhost:3000/api/posts

###