//Listar
GET http://localhost:3000/api/users

###

//Criar
POST http://localhost:3000/api/users
Content-Type:  application/json
 
 {
    "firstName": "Marco",
    "lastName": "Hansen"
 }

//Deletar
###

DELETE http://localhost:3000/api/users/1

###

//Atualizar usuários
PATCH  http://localhost:3000/api/users/3
Content-Type:  application/json
 
 {
    "firstName": "Fulaninhos",
    "lastName": "Hansen"
 }

###

GET http://localhost:3000/api/users/3

###

PATCH http://localhost:3000/api/users/3/toggle

###
//Listar Ativos
GET http://localhost:3000/api/users/active

###
//
