//Listar
GET http://localhost:3000/api/users

###

//Criar
POST http://localhost:3000/api/users
Content-Type:  application/json
 
 {
   
 }

//Deletar
###

DELETE http://localhost:3000/api/users/999

###

//UPDATE - Atualizar usuários
PATCH  http://localhost:3000/api/users/999
Content-Type:  application/json
 
 {
    "firstName": "Fulaninhos",
    "lastName": "Hansen"
 }

###
//List By ID
GET http://localhost:3000/api/users/10

###

PATCH http://localhost:3000/api/users/3/toggle

###
//Listar Ativos
GET http://localhost:3000/api/users/active

###
//
